// <auto-generated />
using System;
using ClasesTallerMecanico.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TallerMecanicoGrupo7.Migrations
{
    [DbContext(typeof(FacturasDBContext))]
    partial class FacturasDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClasesTallerMecanico.Models.CategoriaTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasTrabajos");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.DetalleFacturaCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdFacturaCompra")
                        .HasColumnType("int");

                    b.Property<int>("IdInsumo")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalCompra")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdFacturaCompra");

                    b.HasIndex("IdInsumo");

                    b.ToTable("DetallesFacturasCompras");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.DetalleFacturaVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("CostoUnitarioInsumoHistorico")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("DescripcionItem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdFactura")
                        .HasColumnType("int");

                    b.Property<int?>("IdInsumoPorTrabajo")
                        .HasColumnType("int");

                    b.Property<int?>("IdTrabajoPorTurno")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalDetalle")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdFactura");

                    b.HasIndex("IdInsumoPorTrabajo");

                    b.HasIndex("IdTrabajoPorTurno");

                    b.ToTable("DetallesFacturasVentas");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.DetalleTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DomicilioTrabajo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("IdLocalidad")
                        .HasColumnType("int");

                    b.Property<int>("IdTurno")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdLocalidad");

                    b.HasIndex("IdTurno")
                        .IsUnique();

                    b.ToTable("DetalleTurno");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.EstadoTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("EstadosTurno");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.FacturaCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaFactura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPagoFactura")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdFormaPago")
                        .HasColumnType("int");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<int>("IdSesionCaja")
                        .HasColumnType("int");

                    b.Property<bool>("Pagado")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalFactura")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdFormaPago");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("IdSesionCaja");

                    b.ToTable("FacturasCompras");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.FacturaVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPagoFactura")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdFormaPago")
                        .HasColumnType("int");

                    b.Property<int>("IdSesionCaja")
                        .HasColumnType("int");

                    b.Property<int>("IdTurno")
                        .HasColumnType("int");

                    b.Property<bool>("Pagado")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalFactura")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdFormaPago");

                    b.HasIndex("IdSesionCaja");

                    b.HasIndex("IdTurno")
                        .IsUnique();

                    b.ToTable("FacturasVentas");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.FormaPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("FormasPago");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Insumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdProveedor");

                    b.ToTable("Insumos");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.InsumoPorTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoInsumo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("IdInsumo")
                        .HasColumnType("int");

                    b.Property<int>("IdTrabajoTurno")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdInsumo");

                    b.HasIndex("IdTrabajoTurno");

                    b.ToTable("InsumosPorTrabajo");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Localidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoPostal")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Localidades");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Maquina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Motor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.ToTable("Maquinas");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("IdLocalidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("IdLocalidad");

                    b.ToTable("Persona");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.SesionCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("SesionesCaja");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.TipoTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("TiposTurno");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Trabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioHsManoObra")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Trabajos");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.TrabajoPorTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DetalleTurnoId")
                        .HasColumnType("int");

                    b.Property<decimal>("HsHombre")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("IdTrabajo")
                        .HasColumnType("int");

                    b.Property<int>("IdTurno")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("TarifaHsHombre")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("DetalleTurnoId");

                    b.HasIndex("IdTrabajo");

                    b.HasIndex("IdTurno");

                    b.HasIndex("IdUsuario");

                    b.ToTable("TrabajosPorTurno");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdMaquina")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoTurno")
                        .HasColumnType("int");

                    b.Property<int?>("TipoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdMaquina");

                    b.HasIndex("TipoId");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Cliente", b =>
                {
                    b.HasBaseType("ClasesTallerMecanico.Models.Persona");

                    b.Property<string>("CondFiscal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CuilCuit")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Proveedor", b =>
                {
                    b.HasBaseType("ClasesTallerMecanico.Models.Persona");

                    b.Property<string>("CondFiscal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CuilCuit")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.ToTable("Proveedor");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Usuario", b =>
                {
                    b.HasBaseType("ClasesTallerMecanico.Models.Persona");

                    b.Property<string>("ContraseñaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.DetalleFacturaCompra", b =>
                {
                    b.HasOne("ClasesTallerMecanico.Models.FacturaCompra", "FacturaCompra")
                        .WithMany("Detalles")
                        .HasForeignKey("IdFacturaCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClasesTallerMecanico.Models.Insumo", "Insumo")
                        .WithMany("DetallesCompra")
                        .HasForeignKey("IdInsumo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FacturaCompra");

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.DetalleFacturaVenta", b =>
                {
                    b.HasOne("ClasesTallerMecanico.Models.FacturaVenta", "FacturaVenta")
                        .WithMany("DetallesFacturaVenta")
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClasesTallerMecanico.Models.InsumoPorTrabajo", "InsumoPorTrabajo")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("IdInsumoPorTrabajo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClasesTallerMecanico.Models.TrabajoPorTurno", "TrabajoPorTurno")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("IdTrabajoPorTurno")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FacturaVenta");

                    b.Navigation("InsumoPorTrabajo");

                    b.Navigation("TrabajoPorTurno");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.DetalleTurno", b =>
                {
                    b.HasOne("ClasesTallerMecanico.Models.Localidad", "Localidad")
                        .WithMany()
                        .HasForeignKey("IdLocalidad");

                    b.HasOne("ClasesTallerMecanico.Models.Turno", "Turno")
                        .WithOne("DetalleTurno")
                        .HasForeignKey("ClasesTallerMecanico.Models.DetalleTurno", "IdTurno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localidad");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.FacturaCompra", b =>
                {
                    b.HasOne("ClasesTallerMecanico.Models.FormaPago", "FormaPago")
                        .WithMany()
                        .HasForeignKey("IdFormaPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClasesTallerMecanico.Models.Proveedor", "Proveedor")
                        .WithMany("FacturasCompra")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClasesTallerMecanico.Models.SesionCaja", "SesionCaja")
                        .WithMany("FacturasCompra")
                        .HasForeignKey("IdSesionCaja")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FormaPago");

                    b.Navigation("Proveedor");

                    b.Navigation("SesionCaja");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.FacturaVenta", b =>
                {
                    b.HasOne("ClasesTallerMecanico.Models.Cliente", "Cliente")
                        .WithMany("FacturasVenta")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClasesTallerMecanico.Models.FormaPago", "FormaPago")
                        .WithMany()
                        .HasForeignKey("IdFormaPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClasesTallerMecanico.Models.SesionCaja", "SesionCaja")
                        .WithMany("FacturasVenta")
                        .HasForeignKey("IdSesionCaja")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ClasesTallerMecanico.Models.Turno", "Turno")
                        .WithOne("FacturaVenta")
                        .HasForeignKey("ClasesTallerMecanico.Models.FacturaVenta", "IdTurno")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("FormaPago");

                    b.Navigation("SesionCaja");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Insumo", b =>
                {
                    b.HasOne("ClasesTallerMecanico.Models.Proveedor", "Proveedor")
                        .WithMany("Insumos")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.InsumoPorTrabajo", b =>
                {
                    b.HasOne("ClasesTallerMecanico.Models.Insumo", "Insumo")
                        .WithMany("InsumosPorTrabajo")
                        .HasForeignKey("IdInsumo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClasesTallerMecanico.Models.TrabajoPorTurno", "TrabajoPorTurno")
                        .WithMany("InsumosConsumidos")
                        .HasForeignKey("IdTrabajoTurno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insumo");

                    b.Navigation("TrabajoPorTurno");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Maquina", b =>
                {
                    b.HasOne("ClasesTallerMecanico.Models.Cliente", "Cliente")
                        .WithMany("Maquinas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Persona", b =>
                {
                    b.HasOne("ClasesTallerMecanico.Models.Localidad", "Localidad")
                        .WithMany("Personas")
                        .HasForeignKey("IdLocalidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.SesionCaja", b =>
                {
                    b.HasOne("ClasesTallerMecanico.Models.Usuario", "Usuario")
                        .WithMany("SesionesCaja")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Trabajo", b =>
                {
                    b.HasOne("ClasesTallerMecanico.Models.CategoriaTrabajo", "CategoriaTrabajo")
                        .WithMany("Trabajos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaTrabajo");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.TrabajoPorTurno", b =>
                {
                    b.HasOne("ClasesTallerMecanico.Models.DetalleTurno", null)
                        .WithMany("TrabajosPorTurno")
                        .HasForeignKey("DetalleTurnoId");

                    b.HasOne("ClasesTallerMecanico.Models.Trabajo", "Trabajo")
                        .WithMany("TrabajosPorTurno")
                        .HasForeignKey("IdTrabajo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClasesTallerMecanico.Models.Turno", "Turno")
                        .WithMany("TrabajosPorTurno")
                        .HasForeignKey("IdTurno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClasesTallerMecanico.Models.Usuario", "Usuario")
                        .WithMany("TrabajosRealizados")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trabajo");

                    b.Navigation("Turno");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Turno", b =>
                {
                    b.HasOne("ClasesTallerMecanico.Models.Cliente", "Cliente")
                        .WithMany("Turnos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClasesTallerMecanico.Models.EstadoTurno", "EstadoTurno")
                        .WithMany()
                        .HasForeignKey("IdEstado");

                    b.HasOne("ClasesTallerMecanico.Models.Maquina", "Maquina")
                        .WithMany("Turnos")
                        .HasForeignKey("IdMaquina")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ClasesTallerMecanico.Models.TipoTurno", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId");

                    b.Navigation("Cliente");

                    b.Navigation("EstadoTurno");

                    b.Navigation("Maquina");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Cliente", b =>
                {
                    b.HasOne("ClasesTallerMecanico.Models.Persona", null)
                        .WithOne()
                        .HasForeignKey("ClasesTallerMecanico.Models.Cliente", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Proveedor", b =>
                {
                    b.HasOne("ClasesTallerMecanico.Models.Persona", null)
                        .WithOne()
                        .HasForeignKey("ClasesTallerMecanico.Models.Proveedor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Usuario", b =>
                {
                    b.HasOne("ClasesTallerMecanico.Models.Persona", null)
                        .WithOne()
                        .HasForeignKey("ClasesTallerMecanico.Models.Usuario", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClasesTallerMecanico.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.CategoriaTrabajo", b =>
                {
                    b.Navigation("Trabajos");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.DetalleTurno", b =>
                {
                    b.Navigation("TrabajosPorTurno");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.FacturaCompra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.FacturaVenta", b =>
                {
                    b.Navigation("DetallesFacturaVenta");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Insumo", b =>
                {
                    b.Navigation("DetallesCompra");

                    b.Navigation("InsumosPorTrabajo");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.InsumoPorTrabajo", b =>
                {
                    b.Navigation("DetallesVenta");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Localidad", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Maquina", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.SesionCaja", b =>
                {
                    b.Navigation("FacturasCompra");

                    b.Navigation("FacturasVenta");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Trabajo", b =>
                {
                    b.Navigation("TrabajosPorTurno");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.TrabajoPorTurno", b =>
                {
                    b.Navigation("DetallesVenta");

                    b.Navigation("InsumosConsumidos");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Turno", b =>
                {
                    b.Navigation("DetalleTurno")
                        .IsRequired();

                    b.Navigation("FacturaVenta")
                        .IsRequired();

                    b.Navigation("TrabajosPorTurno");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Cliente", b =>
                {
                    b.Navigation("FacturasVenta");

                    b.Navigation("Maquinas");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Proveedor", b =>
                {
                    b.Navigation("FacturasCompra");

                    b.Navigation("Insumos");
                });

            modelBuilder.Entity("ClasesTallerMecanico.Models.Usuario", b =>
                {
                    b.Navigation("SesionesCaja");

                    b.Navigation("TrabajosRealizados");
                });
#pragma warning restore 612, 618
        }
    }
}
